### ISSUE TITLE
Migrate to .NET SDK projects

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#314]
Work to do:

* [x] https://github.com/dotnet/sdk/issues/939 Work out how to build the code generation assembly before each PInvoke library
* [x] Migrate the projects that make up each library into just one .NET SDK project that multi-targets and packs itself. Each test project (or set of test projects) for a library should also be migrated.
* [x] https://github.com/dotnet/roslyn/issues/17570 Crash when DPL is turned ON
* [x] https://github.com/NuGet/Home/issues/4753 Package restore of sln fails, but each individual project succeeds. Stinky workaround applied.
* [x] Update template
* [x] Update build.ps1 and related scripts
* [x] Update CONTRIBUTING.md documentation on required software to include VS 2017
* [x] Ensure *.pinvokes.txt files are properly generated by the build
* [X] ~Look for `#if DESKTOP` and replace with `#if NET40`~ Define `DESKTOP` symbol as appropriate
* [x] xunit/xunit#1152 xunit test runner on appveyor throws and hangs

**Major usability issues**

* [ ] https://github.com/NuGet/Home/issues/4764 Package restore fails horribly in VS
* [x] https://github.com/dotnet/roslyn/issues/17613 Roslyn design-time builds sometimes fail
* [ ] https://github.com/dotnet/roslyn/issues/17614 https://github.com/dotnet/roslyn-project-system/issues/1696 Roslyn reports hundreds of errors in error list
* [ ] Significant VS responsive issues when the solution is loaded
* [x] Language service never seems to get reference assemblies for projects under DPL mode, resulting in red squiggles virtually *everywhere*
* [ ] Closing solution (with lightweight solution load activated) takes *minutes* - due to design-time builds running that include code generation.
* [ ] With DPL turned off, the solution doesn't fully load -- ASL pauses after the project loads that holds the previously open document. Or pauses when I move focus to another app, and it never resumes.

**Build issues**

* [x] Avoid overbuilding `CodeGeneration` project when building the whole solution.

* [x] Fix over copying of test assets
> C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(4320,5): warning MSB3026: Could not copy "C:\Users\andarno\.nuget
\packages\xunit.runner.visualstudio\2.2.0\build\_common\xunit.abstractions.dll" to "C:\git\pinvoke\src\..\bin\Debug\net46\xunit.abstractions.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\git\pinvoke\src\..\bin\Debug\net46\xunit.abstractions.dll' because it is being used by another process. [C:\git\pinvoke\src\AdvApi32.Tests\AdvApi32.Tests.csproj]

**Comment by arlm** [comment]
Would this include #263 also?

**Comment by AArnott** [comment]
Yes: it would make .netstandard support trivial. As would net20 support if we want.

**Comment by AArnott** [comment]
Work is underway in the dev/andarno/fix314 branch.
