### ISSUE TITLE
<processthreadsapi.h> API's

### ISSUE THREAD

**Issue by vatsan-madhavan** [AArnott/pinvoke#491]
As a follow-up to #428, I started looking into the rest of the API's missing from `<processthreadsapi.h>`.  This is what I found so far: 

## Functions 

- [x] FlushInstructionCache
- [x] FlushProcessWriteBuffers
- [x] GetCurrentProcessorNumber
- [x] GetCurrentProcessorNumberEx
- [x] GetCurrentProcessToken
- [x] GetCurrentThread
- [x] GetCurrentThreadEffectiveToken
- [x] GetCurrentThreadStackLimits
- [x] GetCurrentThreadToken
- [x] GetPriorityClass
- [x] GetProcessHandleCount
- [x] GetProcessIdOfThread
- [ ] GetProcessInformation
- [ ] GetProcessMitigationPolicy
- [ ] GetProcessPriorityBoost
- [ ] GetProcessShutdownParameters
- [ ] GetProcessVersion
- [ ] GetSystemTimes
- [ ] GetThreadContext
- [ ] GetThreadDescription
- [ ] GetThreadId
- [ ] GetThreadIdealProcessorEx
- [ ] GetThreadInformation
- [ ] GetThreadIOPendingFlag
- [ ] GetThreadPriority
- [ ] GetThreadPriorityBoost
- [ ] GetThreadTimes
- [ ] IsProcessCritical
- [ ] IsProcessorFeaturePresent
- [ ] OpenProcessToken
- [ ] OpenThread
- [ ] OpenThreadToken
- [ ] ProcessIdToSessionId
- [ ] QueryProcessAffinityUpdateMode
- [ ] QueryProtectedPolicy
- [ ] QueueUserAPC
- [ ] SetPriorityClass
- [ ] SetProcessAffinityUpdateMode
- [ ] SetProcessDynamicEHContinuationTargets
- [ ] SetProcessInformation
- [ ] SetProcessMitigationPolicy
- [ ] SetProcessPriorityBoost
- [ ] SetProtectedPolicy
- [ ] SetThreadContext
- [ ] SetThreadDescription
- [ ] SetThreadIdealProcessor
- [ ] SetThreadIdealProcessorEx
- [ ] SetThreadInformation
- [ ] SetThreadPriority
- [ ] SetThreadPriorityBoost
- [ ] SetThreadStackGuarantee
- [ ] SetThreadToken
- [ ] SwitchToThread
- [ ] TlsAlloc
- [ ] TlsFree
- [ ] TlsGetValue
- [ ] TlsSetValue

## Structs/types

- [ ] APP_MEMORY_INFORMATION
- [ ] MEMORY_PRIORITY_INFORMATION
- [ ] PROCESS_LEAP_SECOND_INFO
- [ ] PROCESS_MEMORY_EXHAUSTION_INFO
- [ ] PROCESS_POWER_THROTTLING_STATE
- [ ] PROCESS_PROTECTION_LEVEL_INFORMATION
- [ ] THREAD_POWER_THROTTLING_STATE
- [ ] PROCESS_INFORMATION_CLASS
- [ ] PROCESS_MEMORY_EXHAUSTION_TYPE
- [x] PROCESSOR_NUMBER

## Additional types 

- [x] ProcessPriorityClass enum
  - An enum for process priority class values like `ABOVE_NORMAL_PRIORITY_CLASS`. This will be useful for functions like `GetPriorityClass`
- [x] ThreadAccess enum
  - An enum with values like `THREAD_ALL_ACCESS`
- [ ] MemoryPriority enum 
  - Memory priority for thread or process
- [ ] ProcessorPowerThrottlingFlags  enum
  - Flags used with PROCESS_POWER_THROTTLING_STATE struct
- [ ] ProcessProtectionLevel enum
  - Process protection level values
- [ ] ProcessLeapSecondInfoFlags  enum
  - Flags used in PROCESS_LEAP_SECOND_INFO fields

I have some of these implemented, and hope to contribute the rest in near future.
